package tampilan;
import java.sql.*;
import koneksi.koneksi;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class datapenduduk extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form datapenduduk
     */
    public datapenduduk() {
        initComponents();
        setLocationRelativeTo(null);
        datatable();
    }

     protected void aktif(){
        txtnik.setEnabled(true);
        txtnama.setEnabled(true);
        txttempatlahir.setEnabled(true);
        txttgllahir.setEnabled(true);
        txtagama.setEnabled(true);
        txtpendidikan.setEnabled(true);
        txtpekerjaan.setEnabled(true);
        txtstatusperkawinan.setEnabled(true);
        txtkewarganegaraan.setEnabled(true);
        txtrtrw.setEnabled(true);
        txtalamat.setEnabled(true);
        txtnik.requestFocus();
    }
    
      protected void kosong(){
        txtnik.setText("");
        txtnama.setText("");
        jeniskelamin1.setSelected(true);
        txttempatlahir.setText("");
        txttgllahir.setText("");
        txtagama.setText("");
        txtpendidikan.setText("");
        txtpekerjaan.setText("");
        txtstatusperkawinan.setText("");
        txtkewarganegaraan.setText("");
        txtrtrw.setText("");
        txtalamat.setText("");
        txtcari.setText("");
    }         
    
        
    protected void datatable(){
      Object[] Baris = {"NIK","NAMA","JENIS_KELAMIN","TEMPAT_LAHIR","TANGGAL_LAHIR","AGAMA","PENDIDIKAN","PEKERJAAN","STATUS_PERKAWINAN","KEWARGANEGARAAN","RT_RW","ALAMAT"};
        tabmode = new DefaultTableModel(null, Baris);
        tabeldatapenduduk.setModel(tabmode);
        
        String sql = "select * from datapenduduk";
        
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("nik");
                String b = hasil.getString("nama");
                String c = hasil.getString("jenis_kelamin");
                String d = hasil.getString("tempat_lahir");
                String e = hasil.getString("tanggal_lahir");
                String f = hasil.getString("agama");
                String g = hasil.getString("pendidikan");
                String h = hasil.getString("pekerjaan");
                String i = hasil.getString("status_perkawinan");
                String j = hasil.getString("kewarganegaraan");
                String k = hasil.getString("rt_rw");
                String l = hasil.getString("alamat");
                
                String[] data={a,b,c,d,e,f,g,h,i,j,k,l};
                tabmode.addRow(data);
            }
            
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblnik = new javax.swing.JLabel();
        lblnama = new javax.swing.JLabel();
        lbljeniskelamin = new javax.swing.JLabel();
        lbltempatlahir = new javax.swing.JLabel();
        lbltgllahir = new javax.swing.JLabel();
        lblagama = new javax.swing.JLabel();
        txtnik = new javax.swing.JTextField();
        txttempatlahir = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtagama = new javax.swing.JTextField();
        lblpekerjaan = new javax.swing.JLabel();
        lblkewarganegaraan = new javax.swing.JLabel();
        lblalamat = new javax.swing.JLabel();
        txtpendidikan = new javax.swing.JTextField();
        txtpekerjaan = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabeldatapenduduk = new javax.swing.JTable();
        lblpendidikan = new javax.swing.JLabel();
        lblstatusperkawinan = new javax.swing.JLabel();
        lblrtrw = new javax.swing.JLabel();
        txtkewarganegaraan = new javax.swing.JTextField();
        txtstatusperkawinan = new javax.swing.JTextField();
        txtrtrw = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        btnbersihkan = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        txtcari = new javax.swing.JTextField();
        lblmasukannama = new javax.swing.JLabel();
        btncari = new javax.swing.JButton();
        jeniskelamin1 = new javax.swing.JRadioButton();
        jeniskelamin2 = new javax.swing.JRadioButton();
        txttgllahir = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA PENDUDUK");

        lblnik.setForeground(new java.awt.Color(255, 255, 255));
        lblnik.setText("NIK");

        lblnama.setForeground(new java.awt.Color(255, 255, 255));
        lblnama.setText("NAMA");

        lbljeniskelamin.setForeground(new java.awt.Color(255, 255, 255));
        lbljeniskelamin.setText("JENIS KELAMIN");

        lbltempatlahir.setForeground(new java.awt.Color(255, 255, 255));
        lbltempatlahir.setText("TEMPAT LAHIR");

        lbltgllahir.setForeground(new java.awt.Color(255, 255, 255));
        lbltgllahir.setText("TGL LAHIR");

        lblagama.setForeground(new java.awt.Color(255, 255, 255));
        lblagama.setText("AGAMA");

        txtagama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtagamaActionPerformed(evt);
            }
        });

        lblpekerjaan.setForeground(new java.awt.Color(255, 255, 255));
        lblpekerjaan.setText("PEKERJAAN");

        lblkewarganegaraan.setForeground(new java.awt.Color(255, 255, 255));
        lblkewarganegaraan.setText("KEWARGANEGARAAN");

        lblalamat.setForeground(new java.awt.Color(255, 255, 255));
        lblalamat.setText("ALAMAT");

        tabeldatapenduduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabeldatapenduduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabeldatapendudukMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabeldatapenduduk);

        lblpendidikan.setForeground(new java.awt.Color(255, 255, 255));
        lblpendidikan.setText("PENDIDIKAN");

        lblstatusperkawinan.setForeground(new java.awt.Color(255, 255, 255));
        lblstatusperkawinan.setText("STATUS PERKAWINAN");

        lblrtrw.setForeground(new java.awt.Color(255, 255, 255));
        lblrtrw.setText("RT/RW");

        txtstatusperkawinan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstatusperkawinanActionPerformed(evt);
            }
        });

        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/6 save.png"))); // NOI18N
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnkeluar.setBackground(new java.awt.Color(204, 0, 0));
        btnkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/2 back.png"))); // NOI18N
        btnkeluar.setText("KELUAR");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        btnbersihkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/3 clear.png"))); // NOI18N
        btnbersihkan.setText("BERSIHKAN");
        btnbersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbersihkanActionPerformed(evt);
            }
        });

        btnubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/4 change.png"))); // NOI18N
        btnubah.setText("UBAH");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/5 delete.png"))); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        jScrollPane1.setViewportView(txtalamat);

        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });

        lblmasukannama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblmasukannama.setForeground(new java.awt.Color(255, 255, 255));
        lblmasukannama.setText("MASUKAN NAMA");

        btncari.setText("CARI");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        buttonGroup1.add(jeniskelamin1);
        jeniskelamin1.setText("Laki - Laki");

        buttonGroup1.add(jeniskelamin2);
        jeniskelamin2.setText("Perempuan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbljeniskelamin)
                                                .addGap(107, 107, 107)
                                                .addComponent(jeniskelamin2))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(lblagama)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtagama, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbltempatlahir)
                                                        .addComponent(lbltgllahir))
                                                    .addGap(26, 26, 26)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jeniskelamin1)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(txttempatlahir, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(txttgllahir, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtnik, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(lblnik)
                                                    .addGap(235, 235, 235))
                                                .addComponent(lblnama, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGap(141, 141, 141)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblstatusperkawinan)
                                            .addComponent(lblpendidikan)
                                            .addComponent(lblpekerjaan)
                                            .addComponent(lblrtrw)
                                            .addComponent(lblkewarganegaraan)
                                            .addComponent(lblalamat)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(244, 244, 244)
                                        .addComponent(jLabel1)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtkewarganegaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtstatusperkawinan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtrtrw, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(292, 292, 292)
                                        .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnubah, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnbersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblmasukannama)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btncari)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(btnkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(467, 467, 467)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpendidikan))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblpekerjaan))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtstatusperkawinan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblstatusperkawinan))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtkewarganegaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblkewarganegaraan))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtrtrw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblrtrw))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblalamat)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnik)
                            .addComponent(txtnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnama)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbljeniskelamin)
                            .addComponent(jeniskelamin1)
                            .addComponent(jeniskelamin2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltempatlahir)
                            .addComponent(txttempatlahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltgllahir)
                            .addComponent(txttgllahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblagama)
                            .addComponent(txtagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsimpan)
                            .addComponent(btnubah)
                            .addComponent(btnhapus)
                            .addComponent(btnbersihkan)
                            .addComponent(btnkeluar))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncari, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmasukannama, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtagamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtagamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtagamaActionPerformed

    private void txtstatusperkawinanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstatusperkawinanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstatusperkawinanActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void btnbersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbersihkanActionPerformed
        kosong();
        datatable();
    }//GEN-LAST:event_btnbersihkanActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        String sql="INSERT INTO datapenduduk values(?,?,?,?,?,?,?,?,?,?,?,?)";//////////
        try{
            PreparedStatement stat=conn.prepareStatement(sql);
            stat.setString(1, txtnik.getText());
            stat.setString(2, txtnama.getText());
            String jeniskelamin="";
            if(jeniskelamin1.isSelected()) jeniskelamin="laki-laki";
            else jeniskelamin="perempuan";
            stat.setString(3, jeniskelamin);
            stat.setString(4, txttempatlahir.getText());
            stat.setString(5, txttgllahir.getText());
            stat.setString(6, txtagama.getText());
            stat.setString(7, txtpendidikan.getText());
            stat.setString(8, txtpekerjaan.getText());
            stat.setString(9, txtstatusperkawinan.getText());
            stat.setString(10, txtkewarganegaraan.getText());
            stat.setString(11, txtrtrw.getText());
            stat.setString(12, txtalamat.getText());
        
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Berhasil Di Simpan" );
            kosong();
            txtnik.requestFocus();
            datatable();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Data Gagal Di Simpan" );
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        try{
            String sql="UPDATE datapenduduk set nama=?, jenis_kelamin=?, tempat_lahir=?, tanggal_lahir=?, agama=?,  pendidikan=?, pekerjaan=?, status_perkawinan=?, kewarganegaraan=?, rt_rw=?, alamat=? WHERE nik=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtnama.getText());
            String jeniskelamin="";
            if(jeniskelamin1.isSelected()) jeniskelamin="laki-laki";
            else jeniskelamin="perempuan";
            stat.setString(2, jeniskelamin);
            stat.setString(3, txttempatlahir.getText());
            stat.setString(4, txttgllahir.getText());
            stat.setString(5, txtagama.getText());
            stat.setString(6, txtpendidikan.getText());
            stat.setString(7, txtpekerjaan.getText());
            stat.setString(8, txtstatusperkawinan.getText());
            stat.setString(9, txtkewarganegaraan.getText());
            stat.setString(10, txtrtrw.getText()); /////////////////////////////
            stat.setString(11, txtalamat.getText());
            stat.setString(12, txtnik.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Berhasil Di Ubah" );
            kosong();
            txtnik.requestFocus();
            datatable();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Data Gagal Di Ubah" );
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int hapus=JOptionPane.showConfirmDialog(null, "Hapus", "Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if(hapus==0){
           String sql="DELETE FROM datapenduduk where nik='"+txtnik.getText()+"'";
           try{
               PreparedStatement stat=conn.prepareStatement(sql);
               stat.executeUpdate();
               JOptionPane.showMessageDialog(null, "Data Berhasil Di Hapus" );
               kosong();
               txtnik.requestFocus();
               datatable();
           }catch(SQLException e){
               JOptionPane.showMessageDialog(null, "Data Gagal Di Hapus" );           
           }
       } 
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        Object[] Baris = {"NIK","NAMA","JENIS_KELAMIN","TEMPAT_LAHIR","TANGGAL_LAHIR","AGAMA","PENDIDIKAN","PEKERJAAN","STATUS_PERKAWINAN","KEWARGANEGARAAN","RT_RW","ALAMAT"};
        tabmode = new DefaultTableModel(null, Baris);
        tabeldatapenduduk.setModel(tabmode);
        
        String sql = "SELECT * FROM datapenduduk WHERE nama like'%"+txtcari.getText()+"%' ";
        try{
            java.sql.Statement stat=conn.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            while(rs.next()){
                String a = rs.getString("nik");
                String b = rs.getString("nama");
                String c = rs.getString("jenis_kelamin");
                String d = rs.getString("tempat_lahir");
                String e = rs.getString("tanggal_lahir");
                String f = rs.getString("agama");
                String g = rs.getString("pendidikan");
                String h = rs.getString("pekerjaan");
                String i = rs.getString("status_perkawinan");
                String j = rs.getString("kewarganegaraan");
                String k = rs.getString("rt_rw");
                String l = rs.getString("alamat");
                
                String[] data ={a,b,c,d,e,f,g,h,i,j,k,l};
                tabmode.addRow(data);
                kosong();
            }
            
        }catch(Exception e){
        
        }
    }//GEN-LAST:event_btncariActionPerformed

    private void tabeldatapendudukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabeldatapendudukMouseClicked
        int bar = tabeldatapenduduk.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        String i = tabmode.getValueAt(bar, 8).toString();
        String j = tabmode.getValueAt(bar, 9).toString();
        String k = tabmode.getValueAt(bar, 10).toString();
        String l = tabmode.getValueAt(bar, 11).toString();
       
        
        txtnik.setText(a);
        txtnama.setText(b);
        if(c.equals("laki-laki")){
            jeniskelamin1.setSelected(true); 
            jeniskelamin2.setSelected(false);
        }
        else {
            jeniskelamin1.setSelected(false); 
            jeniskelamin2.setSelected(true);
        }
        txttempatlahir.setText(d);
        txttgllahir.setText(e);
        txtagama.setText(f);
        txtpendidikan.setText(g);
        txtpekerjaan.setText(h);
        txtstatusperkawinan.setText(i);
        txtkewarganegaraan.setText(j);
        txtrtrw.setText(k);
        txtalamat.setText(l);
    }//GEN-LAST:event_tabeldatapendudukMouseClicked

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        new menuutama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datapenduduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datapenduduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datapenduduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datapenduduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datapenduduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbersihkan;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton jeniskelamin1;
    private javax.swing.JRadioButton jeniskelamin2;
    private javax.swing.JLabel lblagama;
    private javax.swing.JLabel lblalamat;
    private javax.swing.JLabel lbljeniskelamin;
    private javax.swing.JLabel lblkewarganegaraan;
    private javax.swing.JLabel lblmasukannama;
    private javax.swing.JLabel lblnama;
    private javax.swing.JLabel lblnik;
    private javax.swing.JLabel lblpekerjaan;
    private javax.swing.JLabel lblpendidikan;
    private javax.swing.JLabel lblrtrw;
    private javax.swing.JLabel lblstatusperkawinan;
    private javax.swing.JLabel lbltempatlahir;
    private javax.swing.JLabel lbltgllahir;
    private javax.swing.JTable tabeldatapenduduk;
    private javax.swing.JTextField txtagama;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtkewarganegaraan;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnik;
    private javax.swing.JTextField txtpekerjaan;
    private javax.swing.JTextField txtpendidikan;
    private javax.swing.JTextField txtrtrw;
    private javax.swing.JTextField txtstatusperkawinan;
    private javax.swing.JTextField txttempatlahir;
    private javax.swing.JTextField txttgllahir;
    // End of variables declaration//GEN-END:variables
}
